Update to use Firebase cloud messaging on Android channel
nyaruka/android-channel pull request #4
Opened 2017-05-01 15:09 UTC by norkans7

2017-05-09 23:52 UTC, nicpottier requested changes
Apart from naming looks good, what did we discover with permissions for SMS?

2017-05-09 23:52 UTC, nicpottier commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
Why prefix these with RapidPro?

2017-05-10 11:43 UTC, norkans7 commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
This is a subclass of FirebaseMessageService, any reason to not use RapidPro?

2017-05-10 11:46 UTC, norkans7 commented
first service intents should use the service class, and the provider need to have expoerted set to true and optionally but as best practice both need to specify a permission to limit who can act on them

2017-05-10 14:15 UTC, ericnewcomer commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
Temba?

2017-05-10 14:22 UTC, norkans7 commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
yep, so I change all of them? or just this one only?

2017-05-10 14:26 UTC, ericnewcomer commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
I'd disregard my comment, I don't see a strong reason to go renaming everything else.

2017-05-10 14:27 UTC, norkans7 commented on app/src/main/java/io/rapidpro/androidchannel/RapidProFirebaseMessageService.java
> +public class RapidProFirebaseMessageService extends FirebaseMessagingService {
sawa

2017-07-19 14:10 UTC, norkans7 commented
@nicpottier @ericnewcomer @rowanseymour please review once again

2017-07-19 15:39 UTC, ericnewcomer requested changes
Have you made sure that you can build a branded version of this? I'm worried that some of the manifest changes and build config stuff here might have broken that.

2017-07-19 15:39 UTC, ericnewcomer commented on packs/src/main/AndroidManifest.xml
> -          package="@CONFIG.APP_PACKAGE_NAME@"
Isn't this important for building the other branded versions?

2017-07-19 15:39 UTC, ericnewcomer commented on packs/src/main/AndroidManifest.xml
> -    <permission android:name="io.rapidpro.androidchannel.SEND_MESSAGE" android:label="SMS Channel"></permission>
I think this may be intentionally ambiguous so as to not confused branded versions

2017-07-19 15:43 UTC, norkans7 commented on packs/src/main/AndroidManifest.xml
> -          package="@CONFIG.APP_PACKAGE_NAME@"
I am using gradle to build now this will do the right thing using applicationID

2017-07-19 15:47 UTC, norkans7 commented on packs/src/main/AndroidManifest.xml
> -          package="@CONFIG.APP_PACKAGE_NAME@"
Ohh no I need one more step in the script for this

2017-07-19 15:47 UTC, ericnewcomer commented on packs/src/main/AndroidManifest.xml
> -          package="@CONFIG.APP_PACKAGE_NAME@"
Right, but did you confirm you can build the TextIt branded version as well? We can't break that workflow.

2017-07-19 15:58 UTC, norkans7 commented on packs/src/main/AndroidManifest.xml
> -    <permission android:name="io.rapidpro.androidchannel.SEND_MESSAGE" android:label="SMS Channel"></permission>
this one is well handled RapidPro is replaced by Brand

2017-07-20 08:10 UTC, norkans7 commented on packs/src/main/AndroidManifest.xml
> -          package="@CONFIG.APP_PACKAGE_NAME@"
Now I confirm I built a branded version too

2017-07-20 14:45 UTC, ericnewcomer approved these changes

2017-07-24 09:33 UTC, merged